# Generated by Django 5.1.5 on 2025-05-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0153_merge_20250422_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='order_priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='Очередность заказа'),
        ),
    ]
