# version: '3.7'
services:

  web:
    build: ./python/
    command: python ./${PROJECT}/manage.py runserver 0.0.0.0:8000
    volumes:
      - ../:/home/sites/${PROJECT}/
    env_file:
      - ./.env 
    ports:
      - 8000:8000
    
