# Generated by Django 5.1.5 on 2025-05-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0087_alter_historicalspecification_id_bitrix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductspecification',
            name='order_priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='Очередность заказа'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='order_priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='Очередность заказа'),
        ),
    ]
